[2021-04-29 06:29:14 DEBUG] [cli:73] ###############################################################################
[2021-04-29 06:29:14 DEBUG] [cli:74] Running command 'run'
[2021-04-29 06:29:14 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-29 06:29:15 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-29 06:29:15 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:29:15 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:29:15 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:29:15 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:29:15 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-29 06:29:15 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:29:15 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:29:15 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:29:16 INFO] [experiment:96] Experiment looks valid
[2021-04-29 06:29:16 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:29:16 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:29:16 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:29:16 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:29:16 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:29:16 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:29:16 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-29 06:29:16 DEBUG] [__init__:39] Initializing controls
[2021-04-29 06:29:16 INFO] [run:342] Steady-state strategy: default
[2021-04-29 06:29:16 INFO] [run:345] Rollbacks strategy: default
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:29:16 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-29 06:29:16 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-29 06:29:16 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-29 06:29:16 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:29:16 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-29 06:29:16 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-29 06:29:16 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:29:16 INFO] [run:553] Playing your experiment's method now...
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 INFO] [activity:161] Action: terminate-app-pod
[2021-04-29 06:29:16 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-29 06:29:16 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:29:16 DEBUG] [actions:197] Found 6 pods in ns 'default'
[2021-04-29 06:29:16 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 INFO] [activity:161] Action: terminate-app-pod
[2021-04-29 06:29:16 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-29 06:29:16 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:29:16 DEBUG] [actions:197] Found 6 pods in ns 'default'
[2021-04-29 06:29:16 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-29 06:29:16 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-29 06:29:16 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-29 06:29:16 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-29 06:29:16 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:29:16 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-29 06:29:16 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:16 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-29 06:29:16 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:29:16 INFO] [run:809] Let's rollback...
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-29 06:29:16 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-29 06:29:16 INFO] [run:421] Experiment ended with status: completed
[2021-04-29 06:29:16 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:29:16 DEBUG] [__init__:72] Cleaning up controls
[2021-04-29 06:29:16 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:29:20 DEBUG] [cli:73] ###############################################################################
[2021-04-29 06:29:20 DEBUG] [cli:74] Running command 'run'
[2021-04-29 06:29:20 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-29 06:29:20 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-29 06:29:20 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:29:20 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:29:20 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:29:20 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:29:20 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-29 06:29:20 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:29:20 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:29:20 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:29:21 INFO] [experiment:96] Experiment looks valid
[2021-04-29 06:29:21 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:29:21 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:29:21 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:29:21 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:29:21 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:29:21 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:29:21 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-29 06:29:21 DEBUG] [__init__:39] Initializing controls
[2021-04-29 06:29:21 INFO] [run:342] Steady-state strategy: default
[2021-04-29 06:29:21 INFO] [run:345] Rollbacks strategy: default
[2021-04-29 06:29:21 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:29:21 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-29 06:29:21 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-29 06:29:21 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:29:21 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:21 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-29 06:29:21 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-29 06:29:21 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:29:21 DEBUG] [probes:277] Found 0 failed and 2 not ready pods
[2021-04-29 06:29:21 DEBUG] [activity:235] Activity failed
[2021-04-29 06:29:21 ERROR] [activity:188]   => failed: chaoslib.exceptions.ActivityFailed: the system is unhealthy
[2021-04-29 06:29:21 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:29:21 WARNING] [hypothesis:200] Probe terminated unexpectedly, so its tolerance could not be validated
[2021-04-29 06:29:21 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:29:21 CRITICAL] [run:477] Steady state probe 'all-apps-are-healthy' is not in the given tolerance so failing this experiment
[2021-04-29 06:29:21 INFO] [run:421] Experiment ended with status: failed
[2021-04-29 06:29:21 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:29:21 DEBUG] [__init__:72] Cleaning up controls
[2021-04-29 06:29:21 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:31:13 DEBUG] [cli:73] ###############################################################################
[2021-04-29 06:31:13 DEBUG] [cli:74] Running command 'run'
[2021-04-29 06:31:13 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-29 06:31:13 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-29 06:31:13 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:31:13 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:31:13 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:31:13 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:31:13 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-29 06:31:13 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:31:13 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:31:13 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:31:14 INFO] [experiment:96] Experiment looks valid
[2021-04-29 06:31:14 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:31:14 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:31:14 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:31:14 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:31:14 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:31:14 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:31:14 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-29 06:31:14 DEBUG] [__init__:39] Initializing controls
[2021-04-29 06:31:14 INFO] [run:342] Steady-state strategy: default
[2021-04-29 06:31:14 INFO] [run:345] Rollbacks strategy: default
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:31:14 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-29 06:31:14 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:14 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-29 06:31:14 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-29 06:31:14 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:31:14 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-29 06:31:14 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:14 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-29 06:31:14 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:31:14 INFO] [run:553] Playing your experiment's method now...
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:14 INFO] [activity:161] Action: terminate-app-pod
[2021-04-29 06:31:14 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-29 06:31:14 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:31:14 DEBUG] [actions:197] Found 6 pods in ns 'default'
[2021-04-29 06:31:14 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:14 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:14 INFO] [activity:161] Action: terminate-app-pod
[2021-04-29 06:31:14 DEBUG] [python:34] Activity 'terminate-app-pod' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/actions.py'
[2021-04-29 06:31:14 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:31:15 DEBUG] [actions:197] Found 6 pods in ns 'default'
[2021-04-29 06:31:15 DEBUG] [activity:182]   => succeeded without any result value
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'method'
[2021-04-29 06:31:15 DEBUG] [run:496] Running steady-state hypothesis after the method
[2021-04-29 06:31:15 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:15 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-29 06:31:15 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-29 06:31:15 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:31:15 DEBUG] [probes:277] Found 0 failed and 0 not ready pods
[2021-04-29 06:31:15 DEBUG] [activity:180]   => succeeded with 'True'
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:15 DEBUG] [hypothesis:211] allowed tolerance is True
[2021-04-29 06:31:15 INFO] [hypothesis:221] Steady state hypothesis is met!
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:31:15 INFO] [run:809] Let's rollback...
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-29 06:31:15 INFO] [rollback:25] No declared rollbacks, let's move on.
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'rollback'
[2021-04-29 06:31:15 INFO] [run:421] Experiment ended with status: completed
[2021-04-29 06:31:15 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:31:15 DEBUG] [__init__:72] Cleaning up controls
[2021-04-29 06:31:15 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:31:17 DEBUG] [cli:73] ###############################################################################
[2021-04-29 06:31:17 DEBUG] [cli:74] Running command 'run'
[2021-04-29 06:31:17 DEBUG] [cli:78] Using settings file '/Users/serry/.chaostoolkit/settings.yaml'
[2021-04-29 06:31:18 DEBUG] [settings:26] The Chaos Toolkit settings file could not be found at '/Users/serry/.chaostoolkit/settings.yaml'.
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'loader'
[2021-04-29 06:31:18 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:31:18 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:31:18 INFO] [experiment:47] Validating the experiment's syntax
[2021-04-29 06:31:18 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:31:18 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:31:18 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:31:18 INFO] [experiment:96] Experiment looks valid
[2021-04-29 06:31:18 DEBUG] [caching:42] Clearing activities cache
[2021-04-29 06:31:18 DEBUG] [caching:25] Building activity cache...
[2021-04-29 06:31:18 DEBUG] [caching:35] Cached 2 activities
[2021-04-29 06:31:18 DEBUG] [configuration:54] Loading configuration...
[2021-04-29 06:31:18 DEBUG] [secret:75] Loading secrets...
[2021-04-29 06:31:18 DEBUG] [secret:92] Secrets loaded
[2021-04-29 06:31:18 INFO] [run:323] Running experiment: What happens if we terminate an instance of the application?
[2021-04-29 06:31:18 DEBUG] [__init__:39] Initializing controls
[2021-04-29 06:31:18 INFO] [run:342] Steady-state strategy: default
[2021-04-29 06:31:18 INFO] [run:345] Rollbacks strategy: default
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:31:18 DEBUG] [run:466] Running steady-state hypothesis before the method
[2021-04-29 06:31:18 INFO] [hypothesis:183] Steady state hypothesis: The app is healthy
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:18 INFO] [activity:161] Probe: all-apps-are-healthy
[2021-04-29 06:31:18 DEBUG] [python:34] Activity 'all-apps-are-healthy' loaded from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/chaosk8s/pod/probes.py'
[2021-04-29 06:31:18 DEBUG] [__init__:65] Using Kubernetes context: default
[2021-04-29 06:31:18 DEBUG] [probes:277] Found 0 failed and 1 not ready pods
[2021-04-29 06:31:18 DEBUG] [activity:235] Activity failed
[2021-04-29 06:31:18 ERROR] [activity:188]   => failed: chaoslib.exceptions.ActivityFailed: the system is unhealthy
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'activity'
[2021-04-29 06:31:18 WARNING] [hypothesis:200] Probe terminated unexpectedly, so its tolerance could not be validated
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'hypothesis'
[2021-04-29 06:31:18 CRITICAL] [run:477] Steady state probe 'all-apps-are-healthy' is not in the given tolerance so failing this experiment
[2021-04-29 06:31:18 INFO] [run:421] Experiment ended with status: failed
[2021-04-29 06:31:18 DEBUG] [__init__:355] No controls to apply on 'experiment'
[2021-04-29 06:31:18 DEBUG] [__init__:72] Cleaning up controls
[2021-04-29 06:31:18 DEBUG] [caching:42] Clearing activities cache
